### ISSUE TITLE
IFEM install

### ISSUE THREAD

**Issue by mtembel** [OPM/IFEM#153] opened 2017-05-14 12:24 UTC
============================
I encountered a problem by trying to installing IFEM from source (dune version 2.4.1), I have the following error, it seems there's an issue with "superlu.hh"
...
[ 41%] Building CXX object CMakeFiles/IFEM.dir/src/LinAlg/ISTLMatrix.C.o
In file included from /usr/local/include/dune/istl/overlappingschwarz.hh:14:0,
from /home/mt/OPM/MODULES/IFEM/src/LinAlg/ISTLSupport.h:21,
from /home/mt/OPM/MODULES/IFEM/src/LinAlg/ISTLSolParams.h:19,
from /home/mt/OPM/MODULES/IFEM/src/LinAlg/ISTLMatrix.h:20,
from /home/mt/OPM/MODULES/IFEM/src/LinAlg/ISTLMatrix.C:14:
/usr/local/include/dune/istl/superlu.hh: In member function ‘void Dune::SuperLU<Dune::BCRSMatrix<Dune::FieldMatrix<K, n, p>, TA> >::decompose()’:
/usr/local/include/dune/istl/superlu.hh:524:25: error: ‘struct SuperLUStat_t’ has no member named ‘expansions’
std::cout<<stat.expansions<<std::endl;
^
In file included from /usr/local/include/dune/istl/overlappingschwarz.hh:14:0,
from /home/mt/OPM/MODULES/IFEM/src/LinAlg/ISTLSupport.h:21,
from /home/mt/OPM/MODULES/IFEM/src/LinAlg/ISTLSolParams.h:19,
from /home/mt/OPM/MODULES/IFEM/src/LinAlg/ISTLMatrix.h:20,
from /home/mt/OPM/MODULES/IFEM/src/LinAlg/ISTLMatrix.C:14:
/usr/local/include/dune/istl/superlu.hh: In member function ‘void Dune::SuperLU<Dune::BCRSMatrix<Dune::FieldMatrix<K, n, p>, TA> >::apply(Dune::SuperLU<Dune::BCRSMatrix<Dune::FieldMatrix<K, n, p>, TA> >::domain_type&, Dune::SuperLU<Dune::BCRSMatrix<Dune::FieldMatrix<K, n, p>, TA> >::range_type&, Dune::InverseOperatorResult&)’:
/usr/local/include/dune/istl/superlu.hh:602:24: error: ‘SLU_DOUBLE’ was not declared in this scope
options.IterRefine=SLU_DOUBLE;
^
/usr/local/include/dune/istl/superlu.hh: In member function ‘void Dune::SuperLU<Dune::BCRSMatrix<Dune::FieldMatrix<K, n, p>, TA> >::apply(T*, T*)’:
/usr/local/include/dune/istl/superlu.hh:685:24: error: ‘SLU_DOUBLE’ was not declared in this scope
options.IterRefine=SLU_DOUBLE;
^
make[2]: *** [CMakeFiles/IFEM.dir/src/LinAlg/ISTLMatrix.C.o] Error 1
make[1]: *** [CMakeFiles/IFEM.dir/all] Error 2
make: *** [all] Error 2
Any suggestion?

**Comment by akva2** [comment] 2017-05-15 08:06
which superlu version do you have ? dune 2.4.1 does not support v5.

**Comment by akva2** [comment] 2017-05-15 08:35
also i very much doubt you need the dune support, so i'd suggest simply passing -DIFEM_USE_ISTL=0 to cmake. istl support is not really complete yet.

**Comment by mtembel** [comment] 2017-05-16 07:31
Great thanks you.
cmake .. -DIFEM_USE_ISTL=0
works for me.

**Comment by mtembel** [comment] 2017-05-16 07:35
I guess I should install tinyxml as I have this error for IFEM-Elasticity compilation:
Scanning dependencies of target Beam
[  5%] Building CXX object Beam/CMakeFiles/Beam.dir/ElasticBar.C.o
[ 11%] Building CXX object Beam/CMakeFiles/Beam.dir/ElasticCable.C.o
[ 16%] Building CXX object Beam/CMakeFiles/Beam.dir/SIMElasticBar.C.o
/home/mt/OPM/MODULES/IFEM-Elasticity/Beam/SIMElasticBar.C:25:21: fatal error: tinyxml.h: No such file or directory
 #include "tinyxml.h"
                     ^
compilation terminated.
make[2]: *** [Beam/CMakeFiles/Beam.dir/SIMElasticBar.C.o] Error 1
make[1]: *** [Beam/CMakeFiles/Beam.dir/all] Error 2
make: *** [all] Error 2
...

**Comment by akva2** [comment] 2017-05-16 07:50
If tinyxml is not on your system it should build and ship embedded in the ifem library. How did you build / install ifem?

**Comment by akva2** [comment] 2017-05-16 07:55
should being the keyword, it currently doesn't.

your distros equivalent of sudo apt-get install libtinyxml-dev will fix it.

in the mean time i'll fix the bug.

**Comment by mtembel** [comment] 2017-05-16 07:57
sudo apt-get install libtinyxml-dev  works fine for me

**Comment by akva2** [comment] 2017-05-16 08:02
header issue fixed in https://github.com/OPM/IFEM/commit/bb3ab78c9c0005ec34646b57ee4b9214c0922c1e

**Comment by mtembel** [comment] 2017-05-16 08:02
After installing all the dependencies, I built IFEM as follows:
> cmake ..  -DIFEM_USE_ISTL=0
>make
 >sudo make install

**Comment by akva2** [comment] 2017-05-16 08:03
yeah i managed to reproduce and fix, thanks.

**Comment by mtembel** [comment] 2017-05-16 08:11
...On IFEM, I had issue with HDF5, I turn it OFF (IFEMOptions.cmake) for the compilation to proceed:  
OPTION(IFEM_USE_HDF5           "Compile with HDF5 support?"           OFF)

**Comment by akva2** [comment] 2017-05-16 08:13
please give more details. btw, you don't have to edit the options file, you can set those from the command line -DIFEM_USE_HDF5=OFF

**Comment by mtembel** [comment] 2017-05-16 08:14
also:
 sudo apt-get install libcereal-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libcereal-dev

**Comment by akva2** [comment] 2017-05-16 08:15
libcereal is only available in ubuntu 16.04+

**Comment by mtembel** [comment] 2017-05-16 08:34
The issue with IFEM, with HDF5 ON:
[ 63%] Building CXX object CMakeFiles/IFEM.dir/src/Utility/HDF5Writer.C.o
In file included from /usr/include/hdf5.h:24:0,
                 from /home/mt/OPM/MODULES/IFEM/src/Utility/HDF5Writer.C:27:
/usr/include/H5public.h:63:20: fatal error: mpi.h: No such file or directory
 #   include <mpi.h>
                    ^
compilation terminated.
make[2]: *** [CMakeFiles/IFEM.dir/src/Utility/HDF5Writer.C.o] Error 1
make[1]: *** [CMakeFiles/IFEM.dir/all] Error 2
make: *** [all] Error 2

**Comment by akva2** [comment] 2017-05-16 08:37
right. you are on an earlier ubuntu. you have to explicitly install libhdf5-serial-dev. you cannot have the serial and the mpi enabled library on your system at the same time (and the mpi enabled is the default). this tortured me for years as well, but sadly it's outside my control. you have to update ubuntu or live with the inconvenience.

**Comment by mtembel** [comment] 2017-05-16 08:38
Ubuntu14LTS ...ok, thanks.

**Comment by mtembel** [comment] 2017-05-16 09:19
what are these 2 file in Test used for:
TestPoroMaterial.C
TestSIMPoroElasticity.C
?

**Comment by akva2** [comment] 2017-05-16 09:21
it's unit tests for the relevant classes. you build and execute using 'make check' or just build the test applications using 'make testapps'

**Comment by mtembel** [comment] 2017-05-16 10:22
Thanks it works:
/IFEM-PoroElasticity/build$ make test
Running tests...
Test project /home/mt/OPM/MODULES/IFEM-PoroElasticity/build
    Start 1: PoroElasticity+Plaxis1DVerif.reg
1/9 Test #1: PoroElasticity+Plaxis1DVerif.reg .............   Passed    0.32 sec
    Start 2: PoroElasticity+Plaxis1DVerif-nonmixed.reg
2/9 Test #2: PoroElasticity+Plaxis1DVerif-nonmixed.reg ....   Passed    0.21 sec
    Start 3: PoroElasticity+OGSBenchmark1D.reg
3/9 Test #3: PoroElasticity+OGSBenchmark1D.reg ............   Passed    0.19 sec
    Start 4: PoroElasticity+OGSBenchmark1D-nonmixed.reg
4/9 Test #4: PoroElasticity+OGSBenchmark1D-nonmixed.reg ...   Passed    0.15 sec
    Start 5: PoroElasticity+Terzhagi.reg
5/9 Test #5: PoroElasticity+Terzhagi.reg ..................   Passed    2.77 sec
    Start 6: PoroElasticity+SoilColumn3D.reg
6/9 Test #6: PoroElasticity+SoilColumn3D.reg ..............   Passed    2.25 sec
    Start 7: PoroElasticity+SoilColumn3D-nonmixed.reg
7/9 Test #7: PoroElasticity+SoilColumn3D-nonmixed.reg .....   Passed    0.65 sec
    Start 8: TestPoroMaterial.Parse
8/9 Test #8: TestPoroMaterial.Parse .......................   Passed    0.01 sec
    Start 9: TestSIMPoroElasticity.Parse
9/9 Test #9: TestSIMPoroElasticity.Parse ..................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 9

**Comment by mtembel** [comment] 2017-05-17 11:51
I got this in building HDF5toVTx:
/HDF5toVTx/build$ make
Scanning dependencies of target HDF5toVTx
[ 50%] Building CXX object CMakeFiles/HDF5toVTx.dir/HDF5toVTx.C.o
/home/mt/OPM/MODULES/Apps/HDF5toVTx/HDF5toVTx.C:14:24: fatal error: HDF5Writer.h: No such file or directory
 #include "HDF5Writer.h"
                        ^
compilation terminated.
make[2]: *** [CMakeFiles/HDF5toVTx.dir/HDF5toVTx.C.o] Error 1

make[1]: *** [CMakeFiles/HDF5toVTx.dir/all] Error 2
make: *** [all] Error 2

**Comment by mtembel** [comment] 2017-05-17 11:58
Inside IFEM, I have :
/IFEM/Apps/HDF5toVTx/build$  cmake ..
Call Stack (most recent call first):
  CMakeLists.txt:12 (FIND_PACKAGE)


CMake Error at /home/mt/OPM/MODULES/IFEM/cmake/Modules/FindIFEM.cmake:117 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:12 (FIND_PACKAGE)


CMake Error at /home/mt/OPM/MODULES/IFEM/cmake/Modules/FindIFEM.cmake:119 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:12 (FIND_PACKAGE)


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
IFEM_LIBRARIES
    linked by target "HDF5toVTx" in directory /home/mt/OPM/MODULES/IFEM/Apps/HDF5toVTx
IFEM_PATH
   used as include directory in directory /home/mt/OPM/MODULES/IFEM/Apps/HDF5toVTx

-- Configuring incomplete, errors occurred!
See also "/home/mt/OPM/MODULES/IFEM/Apps/HDF5toVTx/build/CMakeFiles/CMakeOutput.log".
See also "/home/mt/OPM/MODULES/IFEM/Apps/HDF5toVTx/build/CMakeFiles/CMakeError.log".

**Comment by akva2** [comment] 2017-05-17 14:18
Move code from current location to some folder outside ifem source. Build system has some path checks and it is trying to use ifem from source tree.

**Comment by mtembel** [comment] 2017-05-17 17:13
Actually I did that as shown on my 1st comment  & and it complains about HDF5Writer.h, the other IFEM modules works fine:
"I got this in building HDF5toVTx:
/HDF5toVTx/build$ make
Scanning dependencies of target HDF5toVTx
[ 50%] Building CXX object CMakeFiles/HDF5toVTx.dir/HDF5toVTx.C.o
/home/mt/OPM/MODULES/Apps/HDF5toVTx/HDF5toVTx.C:14:24: fatal error: HDF5Writer.h: No such file or directory
#include "HDF5Writer.h"
^
compilation terminated.
make[2]: *** [CMakeFiles/HDF5toVTx.dir/HDF5toVTx.C.o] Error 1

make[1]: *** [CMakeFiles/HDF5toVTx.dir/all] Error 2
make: *** [all] Error 2 
"

**Comment by akva2** [comment] 2017-05-18 07:51
fixed in HEAD.

**Comment by VikingScientist** [comment] 2017-09-07 07:34
Is this fixed? Can we close the issue now?

**Comment by VikingScientist** [comment] 2017-09-29 08:58
This is closed due to inactivity

**Closed by VikingScientist** 2017-09-29 08:58 UTC
